INSERT INTO trend_cards (
  id,
  market,
  seed,
  product_type,
  opportunity_score,
  confidence,
  available_sources,
  missing_sources,
  trend_series,
  reference_images,
  competitors,
  recommendation,
  freshness_tier,
  updated_at
)
VALUES
  (
    'trend-retro-halloween-cats',
    'US',
    'retro halloween cats',
    't-shirt',
    84,
    0.91,
    '["google_trends", "reddit", "amazon", "etsy", "meta_ads"]'::jsonb,
    '["tiktok"]'::jsonb,
    '[{"t": "2026-08-06", "v": 38}, {"t": "2026-08-13", "v": 52}, {"t": "2026-08-20", "v": 67}, {"t": "2026-08-27", "v": 84}]'::jsonb,
    '["https://tos.example/retro-halloween-cats.png"]'::jsonb,
    '[{"title": "Retro Halloween Cat Shirt", "price": 24.99, "adActive": true}, {"title": "Spooky Cat Club Tee", "price": 21.5, "adActive": false}]'::jsonb,
    '{"action": "Launch a vintage cat graphic before the October demand peak.", "reasoning": "Search growth is accelerating while active-ad competition remains moderate."}'::jsonb,
    'hot',
    '2026-08-28T02:00:00.000Z'::timestamptz
  ),
  (
    'trend-coastal-grandma-christmas',
    'US',
    'coastal grandma christmas',
    'mug',
    76,
    0.86,
    '["google_trends", "pinterest", "amazon", "etsy", "meta_ads"]'::jsonb,
    '["tiktok", "reddit"]'::jsonb,
    '[{"t": "2026-08-06", "v": 31}, {"t": "2026-08-13", "v": 45}, {"t": "2026-08-20", "v": 59}, {"t": "2026-08-27", "v": 73}]'::jsonb,
    '["https://tos.example/coastal-christmas.png"]'::jsonb,
    NULL,
    '{"action": "Test understated nautical holiday artwork on giftable products.", "reasoning": "Pinterest saves and marketplace demand are rising ahead of seasonal listings."}'::jsonb,
    'hot',
    '2026-08-27T18:00:00.000Z'::timestamptz
  ),
  (
    'trend-bookish-winter-club',
    'DE',
    'bookish winter club',
    'sweatshirt',
    69,
    0.78,
    '["google_trends", "reddit", "pinterest", "etsy"]'::jsonb,
    '["tiktok", "amazon", "meta_ads"]'::jsonb,
    '[{"t": "2026-08-06", "v": 42}, {"t": "2026-08-13", "v": 46}, {"t": "2026-08-20", "v": 55}, {"t": "2026-08-27", "v": 64}]'::jsonb,
    '["https://tos.example/bookish-winter.png"]'::jsonb,
    NULL,
    '{"action": "Validate cozy reading-club typography with a small winter collection.", "reasoning": "Culture signals are positive, but missing commerce and ads data lowers confidence."}'::jsonb,
    'warm',
    '2026-08-26T10:00:00.000Z'::timestamptz
  )
ON CONFLICT (id) DO UPDATE SET
  market = EXCLUDED.market,
  seed = EXCLUDED.seed,
  product_type = EXCLUDED.product_type,
  opportunity_score = EXCLUDED.opportunity_score,
  confidence = EXCLUDED.confidence,
  available_sources = EXCLUDED.available_sources,
  missing_sources = EXCLUDED.missing_sources,
  trend_series = EXCLUDED.trend_series,
  reference_images = EXCLUDED.reference_images,
  competitors = EXCLUDED.competitors,
  recommendation = EXCLUDED.recommendation,
  freshness_tier = EXCLUDED.freshness_tier,
  updated_at = EXCLUDED.updated_at;
